# Generated by Django 5.2.9 on 2026-01-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_serviceindexpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceIndexPage',
            new_name='ServicesIndexPage',
        ),
        migrations.RenameModel(
            old_name='ServicePage',
            new_name='ServicesPage',
        ),
    ]
