# Generated by Django 5.2.9 on 2026-01-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_serviceindexpage_servicesindexpage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesIndexPage',
            new_name='ServiceIndexPage',
        ),
        migrations.RenameModel(
            old_name='ServicesPage',
            new_name='ServicePage',
        ),
    ]
