# Generated by Django 5.2.9 on 2026-01-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_servicesindexpage_serviceindexpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='intro',
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='portfolio_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
