# Generated by Django 5.2.9 on 2026-01-13 04:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_portfoliopage_body_remove_portfoliopage_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='portfolio_subtitle',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='portfolio_title',
        ),
        migrations.AddField(
            model_name='portfolioindexpage',
            name='portfolio_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='portfolioindexpage',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
