# Generated by Django 5.2.9 on 2026-01-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_projectpage_categories_projectpagetag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
