# Generated by Django 5.2.9 on 2026-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_projectpage_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
