# Generated by Django 5.2.9 on 2026-01-16 18:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_projectpage_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_FAQ_Section',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_tagline',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
