# Generated by Django 5.2.9 on 2026-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_projectpage_project_faq_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_FAQ_tagline',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
