# Generated by Django 5.2.9 on 2026-01-16 22:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projectpage_project_faq_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_conclusion_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_conclusion_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
