# Generated by Django 5.2.9 on 2026-01-16 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_contactformpage_contactformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.contactformpage'),
        ),
    ]
