# Generated by Django 5.2.9 on 2026-01-17 01:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_projectpage_contact_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='client',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='end_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_requirement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_result',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_gallery',
            field=wagtail.fields.StreamField([('gallery_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')]}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo URL or MP4 link', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='start_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='website',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
