# Generated by Django 5.2.9 on 2026-01-17 02:13

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_servicepage_body_remove_servicepage_intro_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        # Drop ContactFormField table first (IF EXISTS — the table may be absent on
        # a fresh MySQL DB) so its FK to ContactFormPage.page_ptr_id is gone before
        # we try to drop that column.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS `portfolio_contactformfield`;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='ContactFormField'),
            ],
        ),
        # Remove all FKs pointing to ContactFormPage.page_ptr_id before dropping it.
        migrations.RemoveField(
            model_name='projectpage',
            name='contact_form',
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='serviceindexpage',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='project_conclusion_description',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='client',
            new_name='project_description',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_FAQ_Section',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_FAQ_tagline',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_conclusion_title',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_subtitle',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_tagline',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='team',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_requirement',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_result',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_gallery',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='website',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='end_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gallery',
            field=wagtail.fields.StreamField([('gallery_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')]}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo URL or MP4 link', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_requirement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_result',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='start_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='website',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_conclusion_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_tagline',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='projectpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='portfolio.servicepage'),
        ),
        migrations.DeleteModel(
            name='ContactFormPage',
        ),
        migrations.DeleteModel(
            name='ServiceIndexPage',
        ),
    ]
