# Generated by Django 5.2.9 on 2026-01-17 02:44

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_contactformpage_servicepage_date_range_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='client',
            new_name='project_conclusion_description',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='project_conclusion_description',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_requirement',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_result',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='website',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='contact_form',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_FAQ_Section',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_FAQ_tagline',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_conclusion_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_subtitle',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_tagline',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='services',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='team',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.contactformpage'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='date_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_FAQ_Section',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_FAQ_tagline',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_conclusion_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_tagline',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_type',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Project categories', through='portfolio.ProjectPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='end_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='gallery',
            field=wagtail.fields.StreamField([('gallery_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')]}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo URL or MP4 link', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_requirement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='project_result',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='start_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='website',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='portfolio.projectpage'),
        ),
    ]

