# Generated by Django 5.2.9 on 2026-01-17 03:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_serviceindexpage_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='project_conclusion_description',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='client',
            new_name='service_conclusion_description',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='description',
            new_name='service_description',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='contact_form',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_FAQ_Section',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_FAQ_tagline',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_conclusion_title',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_subtitle',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_tagline',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='team',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_requirement',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='project_result',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='website',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='end_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gallery',
            field=wagtail.fields.StreamField([('gallery_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')]}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo URL or MP4 link', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_requirement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_result',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='start_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='website',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_FAQ_Section',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_FAQ_tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_conclusion_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}),
        ),
    ]
