# Generated by Django 5.2.9 on 2026-01-18 02:10

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_projectpage_hero_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Project categories (branding, design, interactive, etc.)', through='portfolio.ProjectPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
