# Generated by Django 5.2.9 on 2026-01-20 04:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_projectpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='single_date',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
