# Generated by Django 5.2.9 on 2026-01-26 00:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_projectpage_single_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='end_date',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='start_date',
            new_name='platforms',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='services',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
