# Generated by Django 5.2.9 on 2026-01-26 01:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_rename_end_date_projectpage_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='reviews',
            field=wagtail.fields.StreamField([('review', 4)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'The review text', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Reviewer name', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Reviewer role or position', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'help_text': 'Number of stars (1-5)', 'max_value': 5, 'min_value': 1}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('name', 1), ('role', 2), ('stars', 3)]], {})}),
        ),
    ]
