# Generated by Django 5.2.9 on 2026-02-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_projectpage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioindexpage',
            name='breadcrumb_home',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='portfolioindexpage',
            name='breadcrumb_portfolio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='portfolioindexpage',
            name='project_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
