# Generated by Django 5.2.9 on 2026-02-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_portfolioindexpage_breadcrumb_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioindexpage',
            name='date_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='portfolioindexpage',
            name='project_summary',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
