# Generated by Django 5.2.9 on 2026-02-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_portfolioindexpage_date_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='breadcrumb_home',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
