# Generated by Django 5.2.9 on 2026-02-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_servicepage_breadcrumb_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='btn_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
