# Generated by Django 5.2.9 on 2026-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_servicepage_btn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='servicelist_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
