# Generated by Django 5.2.9 on 2026-02-08 20:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_servicepage_servicelist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='services_list',
            field=wagtail.fields.StreamField([('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='services_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
