# Generated by Django 5.2.9 on 2026-02-08 22:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_serviceindexpage_services_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='about_subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='about_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='video_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceindexpage',
            name='services_list',
            field=wagtail.fields.StreamField([('service', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Service Items'}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('link', 2), ('items', 6)]], {})}),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Service Items'}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('link', 2), ('items', 6)]], {})}),
        ),
    ]
