# Generated by Django 5.2.9 on 2026-02-09 01:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_serviceindexpage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='reviews',
            field=wagtail.fields.StreamField([('review', 5)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'The review text', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Reviewer name', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Reviewer role or position', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'help_text': 'Number of stars (1-5)', 'max_value': 5, 'min_value': 1}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional background image for this review', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('quote', 0), ('name', 1), ('role', 2), ('stars', 3), ('background', 4)]], {})}),
        ),
    ]
