# Generated by Django 5.2.9 on 2026-02-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_serviceindexpage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='btn_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='contact_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='contact_subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
