# Generated by Django 5.2.9 on 2026-02-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_serviceindexpage_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='breadcrumb_home',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='breadcrumb_services',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
