# Generated by Django 5.2.9 on 2026-02-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_serviceindexpage_breadcrumb_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
