# Generated by Django 5.2.9 on 2026-02-09 02:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_serviceindexpage_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='info_client',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='info_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='info_industry',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='info_platforms',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='info_requirement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='info_services',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
