# Generated by Django 5.2.9 on 2026-02-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_projectpage_info_client_projectpage_info_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='client',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='info_client',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='info_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='info_industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='info_platforms',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='info_requirement',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='info_services',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='platforms',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='services',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='single_date',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
