# Generated by Django 5.2.9 on 2026-02-09 02:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_alter_projectpage_client_alter_projectpage_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='platforms',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='services',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='website',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
