# Generated by Django 5.2.9 on 2026-02-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_alter_projectpage_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='info_date',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='info_website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
