# Generated by Django 5.2.9 on 2026-02-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_projectpage_project_result_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='btn_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
