# Generated by Django 5.2.17 on 2026-08-26 20:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_projectpage_btn_text'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(blank=True, max_length=250)),
                ('intro_subtitle', models.CharField(blank=True, max_length=250)),
                ('breadcrumb_home', models.CharField(blank=True, max_length=150)),
                ('breadcrumb_current', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlatformPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated: Django, Wagtail, Python 3.12', max_length=500)),
                ('demo_url', models.URLField(blank=True)),
                ('demo_label', models.CharField(blank=True, default='Try the Demo', max_length=100)),
                ('status', models.CharField(choices=[('live', 'Live'), ('coming_soon', 'Coming Soon')], default='live', max_length=20)),
                ('breadcrumb_home', models.CharField(blank=True, max_length=150)),
                ('breadcrumb_platforms', models.CharField(blank=True, max_length=150)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]

