# Generated by Django 5.2.17 on 2026-08-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_platformindexpage_booking_platformpage_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformpage',
            name='outcome',
            field=models.TextField(blank=True, help_text="2–3 outcome-focused bullet points, one per line. E.g. 'Clients self-serve 80% of recurring requests'"),
        ),
    ]
