# Generated by Django 5.2.9 on 2026-01-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxvideo',
            new_name='parralaxBGVideo',
        ),
    ]
