# Generated by Django 5.2.9 on 2026-01-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_parralaxvideo_homepage_parralaxbgvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxBGVideo',
            new_name='video',
        ),
    ]
