# Generated by Django 5.2.9 on 2026-01-09 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_parralaxbgvideo_homepage_video'),
        ('wagtailembeds', '0009_embed_cache_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='video',
        ),
        migrations.AddField(
            model_name='homepage',
            name='parralaxVideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailembeds.embed'),
        ),
    ]
