# Generated by Django 5.2.9 on 2026-01-09 22:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_video_homepage_parralaxvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='parralaxTitle',
            field=wagtail.fields.RichTextField(blank=True, max_length=50),
        ),
    ]
