# Generated by Django 5.2.9 on 2026-01-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_parralaxtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='parralaxButtonLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
