# Generated by Django 5.2.9 on 2026-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_parralaxbuttonlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='parralaxTitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
