# Generated by Django 5.2.9 on 2026-01-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_parralaxtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxButtonLink',
            new_name='parralax_ButtonLink',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxButtonText',
            new_name='parralax_ButtonText',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxSubtitle',
            new_name='parralax_Subtitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxTitle',
            new_name='parralax_Title',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='parralaxVideo',
            new_name='parralax_Video',
        ),
    ]
