# Generated by Django 5.2.9 on 2026-01-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_parralaxbuttonlink_homepage_parralax_buttonlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_Subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
