# Generated by Django 5.2.9 on 2026-01-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_about_description_homepage_about_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_ButtonLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_ButtonText',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
