# Generated by Django 5.2.9 on 2026-01-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_about_buttonlink_homepage_about_buttontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='portfolio_one_ButtonLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_one_ButtonText',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_one_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_one_Subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_one_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_three_ButtonLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_three_ButtonText',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_three_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_three_Subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_three_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_two_ButtonLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_two_ButtonText',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_two_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_two_Subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_two_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
