# Generated by Django 5.2.9 on 2026-01-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_portfolio_one_buttonlink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='body',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_Subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
