# Generated by Django 5.2.9 on 2026-01-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_contactpage_body_contactpage_contact_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_Subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
