# Generated by Django 5.2.9 on 2026-01-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_contactpage_contact_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_Subtitle',
            field=models.CharField(blank=True),
        ),
    ]
