# Generated by Django 5.2.9 on 2026-01-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_contactpage_contact_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_Subtitle',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
