# Generated by Django 5.2.9 on 2026-01-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactpage_thank_you_text_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
