# Generated by Django 5.2.9 on 2026-01-10 02:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contactpage_faq_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='FAQ_Section',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}),
        ),
    ]
