# Generated by Django 5.2.9 on 2026-01-19 00:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_legalpage_alter_contactpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='legal_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
