# Generated by Django 5.2.9 on 2026-01-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_legalpage_legal_text_legalpage_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalpage',
            old_name='sub_title',
            new_name='Legal_sub_title',
        ),
        migrations.RenameField(
            model_name='legalpage',
            old_name='body',
            new_name='legal_body',
        ),
        migrations.AddField(
            model_name='legalpage',
            name='legal_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
