# Generated by Django 5.2.9 on 2026-01-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_sub_title_legalpage_legal_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalpage',
            name='legal_body',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='legal_title',
        ),
    ]
