# Generated by Django 5.2.9 on 2026-01-20 04:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_aboutpage_alter_contactpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='legalpage',
            options={'verbose_name': 'Legal Page'},
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_Subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
