# Generated by Django 5.2.10 on 2026-01-20 21:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_aboutpage_options_alter_contactpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_list',
            field=wagtail.fields.StreamField([('service', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Service Items'}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('link', 2), ('items', 6)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
