# Generated by Django 5.2.9 on 2026-02-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_contactpage_from_address_contactpage_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='ContactFormField',
        ),
    ]
