# Generated by Django 5.2.9 on 2026-02-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_contactpage_from_address_contactpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='box_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='box_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='box_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='btn_Text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='faq_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
