# Generated by Django 5.2.9 on 2026-02-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_contactpage_box_address_contactpage_box_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='breadcrumb_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='breadcrumb_home',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
