# Generated by Django 5.2.9 on 2026-02-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_contactpage_breadcrumb_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='breadcrumb_home',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
