# Generated by Django 5.2.9 on 2026-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_aboutpage_breadcrumb_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_other_message_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_thank_you_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
