# Generated by Django 5.2.9 on 2026-02-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_contactpage_form_other_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_button_text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
