# Generated by Django 5.2.9 on 2026-02-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_homepage_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='parralax_Video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
