# Generated by Django 5.2.9 on 2026-01-06 01:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliopagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.portfoliopage'),
        ),
    ]
