# Generated by Django 5.2.9 on 2026-02-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Label for the right-side button (e.g. Showcase)', max_length=50),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
