# Generated by Django 5.2.9 on 2026-02-11 02:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_mainmenu_cta_label_mainmenu_cta_page'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=255)),
                ('about_text', wagtail.fields.RichTextField()),
                ('contact_title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('legal_title', models.CharField(max_length=255)),
                ('terms_url', models.URLField()),
                ('privacy_url', models.URLField()),
                ('cookie_url', models.URLField()),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='wagtailcore.site')),
            ],
        ),
    ]
