# Generated by Django 5.2.9 on 2026-02-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_footersnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersnippet',
            name='cookie_label',
            field=models.CharField(default='Cookie Policy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='copyright_text',
            field=models.CharField(default='Catalystdev Web Design. All rights reserved.', help_text='Use {year} where the year should appear', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='email_label',
            field=models.CharField(default='Email', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='privacy_label',
            field=models.CharField(default='Privacy Policy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='terms_label',
            field=models.CharField(default='Terms and Conditions', max_length=255),
            preserve_default=False,
        ),
    ]
