# Generated by Django 4.2.30 on 2026-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_footersnippet_cookie_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='css_class',
            field=models.CharField(blank=True, default='', help_text="Optional CSS class(es) added to this nav item's <li> and <a> (e.g. menu-item--demo)", max_length=100),
        ),
    ]
