# Generated by Django 4.2.30 on 2026-08-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_menuitem_css_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
